app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls.conf import include
from .views import home,cadastrar,produto,perfil
from .classes import password_reset , password_reset_done, password_reset_confirm, password_reset_complete
from app import views 




urlpatterns = [
    path('', home),
    path('cadastro', cadastrar, name="cadatroCliente"),
    path('produto', produto, name='produto'),
    path('perfil', perfil, name='perfil'), 
    path('resetPassword/', password_reset , name='resetPassword'),
    path('cart/', include("carts.urls", namespace="cart")),
    path('resetPassword/password_reset_done/', password_reset_done , name='password_reset_done'),
    path('reset/<uidb64>/<token>/', password_reset_confirm , name='password_reset_confirm '),
    path('reset/done', password_reset_complete, name='password_reset_complete'),

    

] 

carts/urls.py
from django.urls import path

app_name = "carts"

from .views import (
                        cart_home, 
                        cart_update,
                        checkout_home,
                        cart_delet
                    )

urlpatterns = [
    path('', cart_home, name='home'),
    path('checkout/', checkout_home, name='checkout'),
    path('update/', cart_update, name='update'),
    path('delete/', cart_delet, name='delete')
]

docesdaleite/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from carts.views import cart_home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls'), name="home"),
    path('contas/', include('django.contrib.auth.urls')),
    path('cart/', cart_home, name='cart'),
    path('__debug__/', include(debug_toolbar.urls))

]

carts/models.py
from django.conf import settings
from django.db import models
from app.models import Produto, Cliente
from django.db.models.signals import pre_save, post_save, m2m_changed
from decimal import Decimal



User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):
    def new_or_get(self, request):
        # breakpoint()
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id = cart_id)
        if qs.count() == 1 and (not qs.first().cart_confirm):
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user = request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user = None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user = user_obj)

class Cart(models.Model):
    user = models.ForeignKey(Cliente, on_delete=models.CASCADE, null = True, blank = True)
    products = models.ManyToManyField(Produto, blank = True)
    total = models.DecimalField(default = 0.00, max_digits=100, decimal_places = 2)
    subtotal = models.DecimalField(default = 0.00, max_digits=100, decimal_places = 2)
    updated = models.DateTimeField(auto_now = True)
    timestamp = models.DateTimeField(auto_now_add = True)
    objects = CartManager()
    cart_confirm = models.BooleanField(default=False)


    def __str__(self):
        return str(self.id)
    


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
  #print(action)
    # breakpoint()
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
    #print(instance.products.all())
    #print(instance.total)
        products = instance.products.all() 
        total = 0 
        for product in products: 
            total += product.preco 
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()
    #print(total) 
        instance.subtotal = total
        instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender = Cart.products.through)

def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        #instance.total = instance.subtotal  + 10 # considere o 10 como uma taxa de entrega
        instance.total = Decimal(instance.subtotal) * Decimal(1) # 8% de taxa
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender = Cart)

carts/views.py
from django.shortcuts import render, redirect
from app.models import Produto
from .models import Cart
from orders.models import Order
from django.contrib import messages



def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    produtos = cart_obj.products.all()
    return render(request, "carts/cart_home.html", {"cart": cart_obj, "produtos": produtos})

def cart_update(request):
    print(request.POST)
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:                                            
            product_obj = Produto.objects.get(id=product_id)
        except Produto.DoesNotExist:
            print("Mostrar mensagem ao usuário, esse produto acabou!")
            return redirect("cart:home")
        cart_obj, new_obj = Cart.objects.new_or_get(request) 
        limitador = {
            "Massa": 1,
            "Recheio": 2,
            "Tamanho": 1,
            "Topping": 1   
        }

        tipo_produto = cart_obj.products.filter(tipo = product_obj.tipo)
        if len(tipo_produto) < limitador[product_obj.tipo]:
            cart_obj.products.add(product_obj)
        else:
            messages.info(request, 'Produo Já Adicionado no carrinho')
            return redirect("carts:home")

            
        
         
        # if product_obj in cart_obj.products.all(): 
        #     cart_obj.products.remove(product_obj) 
        # else: 
        request.session['cart_items'] = cart_obj.products.count()
    return redirect("cart:home")

def cart_delet(request):
    product_id = request.POST.get('product_id')
    product_obj = Produto.objects.get(id = product_id)
    cart_obj, new_obj = Cart.objects.new_or_get(request) 
    if product_obj in cart_obj.products.all(): 
        cart_obj.products.remove(product_obj)
    return redirect("cart:home") 
 
def checkout_home(request):
    #aqui a gente pega o carrinho
    cart_obj, cart_created= Cart.objects.new_or_get(request)
    order_obj = None
    #se o carrinho acabou de ser criado, ele tá zerado
    #ou se o carrinho já existir mas não tiver nada dentro
    produtos = cart_obj.products.all()
    if cart_created or cart_obj.products.count() == 0:
        return redirect("cart:home")
    #aqui a order associada ao carrinho
    else:
        order_obj, new_order_obj = Order.objects.get_or_create(cart = cart_obj, client_id = cart_obj.user_id, data_compra = cart_obj.timestamp.today() )

    return render(request, "carts/checkout.html", {"object": order_obj, "produtos":produtos})

carts/templates/carts/cart_home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static%}

{%block conteudo%}
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-danger" role="alert" {% endif %}>
    <p>{{ message }}</p>
</div>
{% endfor %}
{% endif %}
<section class="carrinho">
    <div class="container">
        <div class="row pt-5 mt-5 flex-wrap">
            <div class="col-12">
                {% if not user.is_anonymous %}
                {% if cart.products.exists %}
                <h1>Carrinho</h1>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nome do produto</th>
                            <th>Preço do produto</th>
                            <th>Remover</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for product in cart.products.all %}
                        <tr>
                            <thscope="1">
                                </th>
                                <td>
                                    <p>{{ product.nome }}</p>
                                </td>
                                <td>R$ {{ product.preco }}</td>
                                <td>{% include 'products/snippets/update-cart.html' with product=product cart=cart in_cart=True%}
                                </td>
                        </tr>
                        {% endfor %}
                        <tr>
                            <td colspan="2"></td>
                            <td colspan="2"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-12">

                <b>Total</b> {{ cart.total }}
                
            </div>
            <div class="col-12 pt-3 text-center">
                <a href="/produto" class="btn btn-primary mr-3">Continuar Comprando</a>
                <a class='btn btn-success' href='{% url "cart:checkout" %}'>Finalizar Pedido</a>
            </div>
        {% else %}
        </div>
        <div class="container">

            <div class="row justify-content-center align-items-center flex-wrap flex-column pt-5 mt-5">
                <h1>Carrinho vazio</h1>
                <p>Se quiser ver os produtos</p>
                <a href="/produto" class="btn btn-primary">Ver produtos</a>
            </div>
        </div>
        {% endif %}
        {% endif %}
    </div>
</section>

{%endblock conteudo%}

carts/templates/carts/checkout.html
{% extends "base.html" %}
{%block conteudo%}
<section class="checkout">
    <div class="container">
        <div class="row justify-content-center flex-column align-items-center">
            <h1>Pedido Finalizado Com Sucesso !</h1>
            <div class="borda-checkout mt-4 text-center">
            {% for produto in produtos %}
                <p>
                    Produto: {{ produto }}
                </p>
                {% endfor %}
                <p>Total:R$ {{ object.total }}</p>
            </div>
            <div class="mt-4">
                <a href="/perfil" class="btn btn-primary">Voltar para o perfil</a>
            </div>
        </div>
    </div>
</section>
{%endblock conteudo%}