app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls.conf import include
from .views import home,cadastrar,produto,perfil
from .classes import password_reset , password_reset_done, password_reset_confirm, password_reset_complete
from app import views 




urlpatterns = [
    path('', home),
    path('cadastro', cadastrar, name="cadatroCliente"),
    path('produto', produto, name='produto'),
    path('perfil', perfil, name='perfil'), 
    path('resetPassword/', password_reset , name='resetPassword'),
    path('cart/', include("carts.urls", namespace="cart")),
    path('resetPassword/password_reset_done/', password_reset_done , name='password_reset_done'),
    path('reset/<uidb64>/<token>/', password_reset_confirm , name='password_reset_confirm '),
    path('reset/done', password_reset_complete, name='password_reset_complete'),

    

] 

carts/urls.py
from django.urls import path

app_name = "carts"

from .views import (
                        cart_home, 
                        cart_update,
                        checkout_home,
                        cart_delet
                    )

urlpatterns = [
    path('', cart_home, name='home'),
    path('checkout/', checkout_home, name='checkout'),
    path('update/', cart_update, name='update'),
    path('delete/', cart_delet, name='delete')
]

docesdaleite/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from carts.views import cart_home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls'), name="home"),
    path('contas/', include('django.contrib.auth.urls')),
    path('cart/', cart_home, name='cart'),
    path('__debug__/', include(debug_toolbar.urls))

]

app/templates/products/snippets/update-cart.html
{% if in_cart %}
{% for produto in produtos %}
<form method='POST' action='{% url "cart:delete" %}' class="form"> {% csrf_token %}
    <input type='hidden' name='product_id' value='{{ produto.id }}' />
{% endfor %}
        <button type='submit' class='btn btn-secondary'>Excluir
            Produto</button>
</form>

{% else %}
<form method='POST' action='{% url "cart:update" %}' class="form"> {% csrf_token %}
    <input type='hidden' name='product_id' value='{{ produto.id }}' />
        <button type='submit' class='btn btn-primary'>Adicionar</button>
</form>
{% endif %}







<!-- <form method='POST' action='{% url "cart:update" %}' class="form"> {% csrf_token %}
    <input type='hidden' name='product_id' value='{{ produto.id }}' />
    {% if in_cart %}
    <form action="{% url 'cart:delete' %}" method="post">
        <button type='submit' class='btn btn-link btn-sm' style="padding:0px;cursor: pointer;">Excluir
            arrombado</button>
    </form>
    {% else %}
    <button type='submit' class='btn btn-success'>Adicionar update cart</button>
    {% endif %}
</form> -->